DELETE FROM "public"."assessment_questions";

INSERT INTO "public"."assessment_questions" ("id","assessment_type","category","text","version","active","parent_id","is_initial","is_advanced","sort_order","updated_at") VALUES
('comm-1','communication','Communication & Relationships','Do you know how to adapt your communication style for different people (e.g., formal vs casual, professional vs personal)?',1,true,NULL,false,false,0,NOW()),
('comm-1-1','communication','Communication & Relationships','Can you confidently write a clear professional email or message?',1,true,'comm-1',false,true,0,NOW()),
('comm-1-2','communication','Communication & Relationships','Do you know how to switch between formal and casual conversation appropriately?',1,true,'comm-1',false,true,0,NOW()),
('comm-1-3','communication','Communication & Relationships','Can you recognise and adapt to non-verbal cues (body language, tone)?',1,true,'comm-1',false,true,0,NOW()),
('comm-1-4','communication','Communication & Relationships','Do you know how to adjust your approach when talking to children, elders, or authority figures?',1,true,'comm-1',false,true,0,NOW()),
('comm-2','communication','Communication & Relationships','How confident are you with conflict resolution in everyday life?',1,true,NULL,false,false,0,NOW()),
('comm-2-1','communication','Communication & Relationships','Can you de-escalate a heated argument calmly?',1,true,'comm-2',false,true,0,NOW()),
('comm-2-2','communication','Communication & Relationships','Do you know how to negotiate a compromise that works for everyone?',1,true,'comm-2',false,true,0,NOW()),
('comm-2-3','communication','Communication & Relationships','Can you stay respectful and constructive when you strongly disagree with someone?',1,true,'comm-2',false,true,0,NOW()),
('comm-2-4','communication','Communication & Relationships','Do you know how to support others in resolving disagreements fairly?',1,true,'comm-2',false,true,0,NOW()),
('comm-3','communication','Communication & Relationships','Do you feel able to express your ideas clearly in group settings (meetings, social events, community)?',1,true,NULL,false,false,0,NOW()),
('comm-3-1','communication','Communication & Relationships','Can you give a short presentation or speech confidently?',1,true,'comm-3',false,true,0,NOW()),
('comm-3-2','communication','Communication & Relationships','Do you know how to keep people engaged while you’re speaking?',1,true,'comm-3',false,true,0,NOW()),
('comm-3-3','communication','Communication & Relationships','Can you encourage quieter people to contribute without pressure?',1,true,'comm-3',false,true,0,NOW()),
('comm-3-4','communication','Communication & Relationships','Do you know how to chair or facilitate a structured discussion?',1,true,'comm-3',false,true,0,NOW()),
('comm-4','communication','Communication & Relationships','Do you actively listen and respond thoughtfully when others share their views?',1,true,NULL,false,false,0,NOW()),
('comm-4-1','communication','Communication & Relationships','Can you summarise what someone has said to show you’ve understood?',1,true,'comm-4',false,true,0,NOW()),
('comm-4-2','communication','Communication & Relationships','Do you know how to ask good follow-up questions to keep conversation flowing?',1,true,'comm-4',false,true,0,NOW()),
('comm-4-3','communication','Communication & Relationships','Can you provide constructive feedback without sounding critical?',1,true,'comm-4',false,true,0,NOW()),
('comm-4-4','communication','Communication & Relationships','Do you know how to notice when someone feels unheard and bring them back into the conversation?',1,true,'comm-4',false,true,0,NOW()),
('comm-5','communication','Communication & Relationships','Do you feel able to express your feelings (e.g., sadness, joy, frustration) openly and appropriately?',1,true,NULL,false,false,0,NOW()),
('comm-5-1','communication','Communication & Relationships','Can you put words to emotions instead of bottling them up?',1,true,'comm-5',false,true,0,NOW()),
('comm-5-2','communication','Communication & Relationships','Do you know how to express vulnerability without feeling ashamed?',1,true,'comm-5',false,true,0,NOW()),
('comm-5-3','communication','Communication & Relationships','Can you support someone else who’s sharing their emotions with you?',1,true,'comm-5',false,true,0,NOW()),
('comm-5-4','communication','Communication & Relationships','Do you know how to communicate emotions without placing blame?',1,true,'comm-5',false,true,0,NOW()),
('comm-6','communication','Communication & Relationships','Do you feel comfortable talking openly with other men about personal challenges or worries?',1,true,NULL,false,false,0,NOW()),
('comm-6-1','communication','Communication & Relationships','Can you reach out to a friend when you need support?',1,true,'comm-6',false,true,0,NOW()),
('comm-6-2','communication','Communication & Relationships','Do you know how to respond if another man confides in you?',1,true,'comm-6',false,true,0,NOW()),
('comm-6-3','communication','Communication & Relationships','Can you create space for honest conversations without judgment?',1,true,'comm-6',false,true,0,NOW()),
('comm-6-4','communication','Communication & Relationships','Do you know how to balance humour and seriousness when checking in on mates?',1,true,'comm-6',false,true,0,NOW()),
('community-1','community','Community & Contribution','How confident are you in taking part in group projects or community initiatives?',1,true,NULL,false,false,0,NOW()),
('community-1-1','community','Community & Contribution','Can you take on specific roles (e.g., treasurer, organiser, coordinator)?',1,true,'community-1',false,true,0,NOW()),
('community-1-2','community','Community & Contribution','Do you know how to plan or schedule community activities?',1,true,'community-1',false,true,0,NOW()),
('community-1-3','community','Community & Contribution','Can you manage logistics like booking venues or arranging equipment?',1,true,'community-1',false,true,0,NOW()),
('community-2','community','Community & Contribution','How comfortable are you supporting people outside your immediate circle (e.g., neighbours, colleagues, strangers)?',1,true,NULL,false,false,0,NOW()),
('community-2-1','community','Community & Contribution','Do you offer help proactively without waiting to be asked?',1,true,'community-2',false,true,0,NOW()),
('community-2-2','community','Community & Contribution','Are you able to balance helping others with your own responsibilities?',1,true,'community-2',false,true,0,NOW()),
('community-2-3','community','Community & Contribution','Can you connect people to the right resources or services when needed?',1,true,'community-2',false,true,0,NOW()),
('community-3','community','Community & Contribution','How confident are you in sharing your skills with others in a useful way?',1,true,NULL,false,false,0,NOW()),
('community-3-1','community','Community & Contribution','Can you explain or demonstrate practical skills step by step?',1,true,'community-3',false,true,0,NOW()),
('community-3-2','community','Community & Contribution','Have you ever created resources (guides, notes, videos) to help others learn?',1,true,'community-3',false,true,0,NOW()),
('community-3-3','community','Community & Contribution','Can you adapt your approach depending on who you are helping?',1,true,'community-3',false,true,0,NOW()),
('community-4','community','Community & Contribution','How confident are you in contributing to the wellbeing of your wider community?',1,true,NULL,false,false,0,NOW()),
('community-4-1','community','Community & Contribution','Do you participate in keeping shared spaces safe, clean, or welcoming?',1,true,'community-4',false,true,0,NOW()),
('community-4-2','community','Community & Contribution','Have you been part of organising or attending community events that bring people together?',1,true,'community-4',false,true,0,NOW()),
('community-4-3','community','Community & Contribution','Can you identify gaps in your community and suggest improvements?',1,true,'community-4',false,true,0,NOW()),
('diy-1','diy','DIY & Repairs','What level are you at with everyday gardening tasks (planting, mowing, pruning)?',1,true,NULL,false,false,0,NOW()),
('diy-1-1','diy','DIY & Repairs','Can you design and maintain a flower bed or vegetable patch?',1,true,'diy-1',false,true,0,NOW()),
('diy-1-2','diy','DIY & Repairs','Do you know how to use powered garden tools (hedge trimmer, strimmer)?',1,true,'diy-1',false,true,0,NOW()),
('diy-1-3','diy','DIY & Repairs','Can you build or repair garden structures (fence, shed, decking)?',1,true,'diy-1',false,true,0,NOW()),
('diy-1-4','diy','DIY & Repairs','Can you install irrigation or drainage systems for a garden?',1,true,'diy-1',false,true,0,NOW()),
('diy-1-5','diy','DIY & Repairs','Do you know how to graft or propagate plants successfully?',1,true,'diy-1',false,true,0,NOW()),
('diy-2','diy','DIY & Repairs','What level are you at with interior improvements (painting, flooring, tiling)?',1,true,NULL,false,false,1,NOW()),
('diy-2-1','diy','DIY & Repairs','Can you safely fit shelving units or cupboards?',1,true,'diy-2',false,true,0,NOW()),
('diy-2-2','diy','DIY & Repairs','Can you install or repair flooring (tiles, laminate, carpet)?',1,true,'diy-2',false,true,0,NOW()),
('diy-2-3','diy','DIY & Repairs','Have you ever completed a room renovation project (kitchen, bathroom, loft)?',1,true,'diy-2',false,true,0,NOW()),
('diy-2-4','diy','DIY & Repairs','Can you carry out basic plastering or wall repairs?',1,true,'diy-2',false,true,0,NOW()),
('diy-2-5','diy','DIY & Repairs','Can you safely remove and replace internal walls or partitions?',1,true,'diy-2',false,true,0,NOW()),
('diy-3','diy','DIY & Repairs','What level are you at with simple plumbing (fixing leaks, changing taps)?',1,true,NULL,false,false,2,NOW()),
('diy-3-1','diy','DIY & Repairs','Can you install or replace a toilet?',1,true,'diy-3',false,true,0,NOW()),
('diy-3-2','diy','DIY & Repairs','Can you fit or repair a shower or bath?',1,true,'diy-3',false,true,0,NOW()),
('diy-3-3','diy','DIY & Repairs','Do you understand basic water pipe layouts (supply vs waste)?',1,true,'diy-3',false,true,0,NOW()),
('diy-3-4','diy','DIY & Repairs','Can you install or replace radiators or a heating system component?',1,true,'diy-3',false,true,0,NOW()),
('diy-3-5','diy','DIY & Repairs','Can you solder or join copper piping confidently?',1,true,'diy-3',false,true,0,NOW()),
('diy-4','diy','DIY & Repairs','What level are you at with car maintenance (oil changes, tyres, battery)?',1,true,NULL,false,false,3,NOW()),
('diy-4-1','diy','DIY & Repairs','Can you replace brake pads or discs?',1,true,'diy-4',false,true,0,NOW()),
('diy-4-2','diy','DIY & Repairs','Can you change a timing belt or alternator?',1,true,'diy-4',false,true,0,NOW()),
('diy-4-3','diy','DIY & Repairs','Do you understand how to diagnose engine warning lights?',1,true,'diy-4',false,true,0,NOW()),
('diy-4-4','diy','DIY & Repairs','Can you service a car fully (oil, filters, spark plugs, coolant, brakes)?',1,true,'diy-4',false,true,0,NOW()),
('diy-4-5','diy','DIY & Repairs','Can you replace a clutch or gearbox?',1,true,'diy-4',false,true,0,NOW()),
('diy-5','diy','DIY & Repairs','What level are you at with common power tools (drill, saw, sander)?',1,true,NULL,false,false,4,NOW()),
('diy-5-1','diy','DIY & Repairs','Can you safely operate and maintain a circular saw or jigsaw?',1,true,'diy-5',false,true,0,NOW()),
('diy-5-2','diy','DIY & Repairs','Have you built furniture or structures using power tools?',1,true,'diy-5',false,true,0,NOW()),
('diy-5-3','diy','DIY & Repairs','Do you understand workshop safety (PPE, ventilation, electrics)?',1,true,'diy-5',false,true,0,NOW()),
('diy-5-4','diy','DIY & Repairs','Can you build fitted furniture (wardrobes, cabinets, or a workbench)?',1,true,'diy-5',false,true,0,NOW()),
('diy-5-5','diy','DIY & Repairs','Can you use advanced tools (router, table saw, lathe) with confidence?',1,true,'diy-5',false,true,0,NOW()),
('diy-6','diy','DIY & Repairs','Do you own a set of basic tools (e.g., screwdriver set, hammer, pliers)?',1,true,NULL,false,false,5,NOW()),
('diy-6-1','diy','DIY & Repairs','Can you sharpen and maintain tools like chisels, saws, or blades?',1,true,'diy-6',false,true,0,NOW()),
('diy-6-2','diy','DIY & Repairs','Do you know how to properly oil/grease and store tools to extend their lifespan?',1,true,'diy-6',false,true,0,NOW()),
('diy-6-3','diy','DIY & Repairs','Can you identify and select the correct tool for a job without guidance?',1,true,'diy-6',false,true,0,NOW()),
('diy-6-4','diy','DIY & Repairs','Do you use safety gear (PPE, eye protection, gloves) consistently when working?',1,true,'diy-6',false,true,0,NOW()),
('diy-6-5','diy','DIY & Repairs','Can you measure and mark accurately using tools like spirit levels, squares, or calipers?',1,true,'diy-6',false,true,0,NOW()),
('init-comm-1','initial','Communication & Relationships','How confident are you at expressing your needs in relationships?',1,true,NULL,true,false,0,NOW()),
('init-comm-2','initial','Communication & Relationships','Are you comfortable giving and receiving feedback?',1,true,NULL,true,false,1,NOW()),
('init-comm-3','initial','Communication & Relationships','Do you find it easy to have difficult conversations without conflict?',1,true,NULL,true,false,2,NOW()),
('init-comm-4','initial','Communication & Relationships','Can you maintain long-term friendships or close connections?',1,true,NULL,true,false,3,NOW()),
('init-commu-1','initial','Community & Contribution','Are you involved in any community or volunteering activities?',1,true,NULL,true,false,4,NOW()),
('init-commu-2','initial','Community & Contribution','Do you feel a sense of responsibility toward others?',1,true,NULL,true,false,5,NOW()),
('init-commu-3','initial','Community & Contribution','Have you ever supported someone else in learning or improving a skill?',1,true,NULL,true,false,6,NOW()),
('init-commu-4','initial','Community & Contribution','Do you make time to contribute beyond your own household?',1,true,NULL,true,false,7,NOW()),
('init-diy-1','initial','DIY & Repairs','How confident are you using basic tools like a hammer or screwdriver?',1,true,NULL,true,false,0,NOW()),
('init-diy-2','initial','DIY & Repairs','Can you assemble flat-pack furniture without help?',1,true,NULL,true,false,1,NOW()),
('init-diy-3','initial','DIY & Repairs','Have you ever repaired something in your home (e.g., a leaking tap, squeaky hinge)?',1,true,NULL,true,false,2,NOW()),
('init-diy-4','initial','DIY & Repairs','Can you hang a shelf or picture securely on a wall?',1,true,NULL,true,false,3,NOW()),
('init-tech-1','initial','Technology & Digital Skills','How confident are you setting up new devices (TV, Wi-Fi, smart home tech)?',1,true,NULL,true,false,0,NOW()),
('init-tech-2','initial','Technology & Digital Skills','Do you know how to keep your computer or phone software up to date?',1,true,NULL,true,false,1,NOW()),
('init-tech-3','initial','Technology & Digital Skills','Can you confidently troubleshoot basic tech issues?',1,true,NULL,true,false,2,NOW()),
('init-tech-4','initial','Technology & Digital Skills','Are you comfortable using tools like spreadsheets or word processors?',1,true,NULL,true,false,3,NOW()),
('init-well-1','initial','Well-being & Self-care','Do you have a regular exercise or movement routine?',1,true,NULL,true,false,0,NOW()),
('init-well-2','initial','Well-being & Self-care','Do you take time to reflect on your mental well-being?',1,true,NULL,true,false,1,NOW()),
('init-well-3','initial','Well-being & Self-care','Can you confidently prepare a healthy meal?',1,true,NULL,true,false,2,NOW()),
('init-well-4','initial','Well-being & Self-care','Do you make time for rest and recovery?',1,true,NULL,true,false,3,NOW()),
('well-1','self-care','Well-being & Self-care','Do you engage in regular physical activity or exercise?',1,true,NULL,false,false,0,NOW()),
('well-1-1','self-care','Well-being & Self-care','Can you confidently design your own workout routine?',1,true,'well-1',false,true,0,NOW()),
('well-1-2','self-care','Well-being & Self-care','Do you know how to perform key compound exercises with good form?',1,true,'well-1',false,true,0,NOW()),
('well-1-3','self-care','Well-being & Self-care','Can you track and progressively improve your fitness over time?',1,true,'well-1',false,true,0,NOW()),
('well-1-4','self-care','Well-being & Self-care','Do you understand how to warm up and cool down safely?',1,true,'well-1',false,true,0,NOW()),
('well-2','self-care','Well-being & Self-care','Do you actively set aside time for mental well-being practices?',1,true,NULL,false,false,0,NOW()),
('well-2-1','self-care','Well-being & Self-care','Do you practice techniques like meditation or journaling?',1,true,'well-2',false,true,0,NOW()),
('well-2-2','self-care','Well-being & Self-care','Can you identify signs of stress or burnout in yourself?',1,true,'well-2',false,true,0,NOW()),
('well-2-3','self-care','Well-being & Self-care','Do you use strategies to manage anxiety or difficult emotions?',1,true,'well-2',false,true,0,NOW()),
('well-2-4','self-care','Well-being & Self-care','Do you maintain healthy digital or work-life boundaries?',1,true,'well-2',false,true,0,NOW()),
('well-3','self-care','Well-being & Self-care','Can you prepare balanced and healthy meals for yourself?',1,true,NULL,false,false,0,NOW()),
('well-3-1','self-care','Well-being & Self-care','Do you know how to cook multiple meals from scratch (not ready meals)?',1,true,'well-3',false,true,0,NOW()),
('well-3-2','self-care','Well-being & Self-care','Can you adapt meals to meet dietary needs (e.g., high-protein, vegetarian)?',1,true,'well-3',false,true,0,NOW()),
('well-3-3','self-care','Well-being & Self-care','Do you understand portion sizes and basic nutrition principles?',1,true,'well-3',false,true,0,NOW()),
('well-3-4','self-care','Well-being & Self-care','Can you confidently follow a recipe and adjust it if ingredients are missing?',1,true,'well-3',false,true,0,NOW()),
('well-4','self-care','Well-being & Self-care','Do you make consistent time for proper rest and recovery?',1,true,NULL,false,false,0,NOW()),
('well-4-1','self-care','Well-being & Self-care','Do you get at least 7–8 hours of quality sleep most nights?',1,true,'well-4',false,true,0,NOW()),
('well-4-2','self-care','Well-being & Self-care','Do you avoid screen use or stimulants before bed?',1,true,'well-4',false,true,0,NOW()),
('well-4-3','self-care','Well-being & Self-care','Do you know relaxation techniques to help you wind down?',1,true,'well-4',false,true,0,NOW()),
('well-4-4','self-care','Well-being & Self-care','Do you regularly schedule downtime without feeling guilty?',1,true,'well-4',false,true,0,NOW()),
('tech-1','technology','Technology & Digital Skills','How comfortable are you with using email, browsing, and managing files?',1,true,NULL,false,false,0,NOW()),
('tech-1-1','technology','Technology & Digital Skills','Can you install and configure new software safely?',1,true,'tech-1',false,true,0,NOW()),
('tech-1-2','technology','Technology & Digital Skills','Do you know how to back up files to the cloud or external drives?',1,true,'tech-1',false,true,0,NOW()),
('tech-1-3','technology','Technology & Digital Skills','Can you troubleshoot common issues like a slow computer or error messages?',1,true,'tech-1',false,true,0,NOW()),
('tech-1-4','technology','Technology & Digital Skills','Can you confidently set up a new computer from scratch (updates, accounts, software)?',1,true,'tech-1',false,true,0,NOW()),
('tech-2','technology','Technology & Digital Skills','How confident are you with setting up and using a smartphone?',1,true,NULL,false,false,0,NOW()),
('tech-2-1','technology','Technology & Digital Skills','Can you move data/photos from one phone to another?',1,true,'tech-2',false,true,0,NOW()),
('tech-2-2','technology','Technology & Digital Skills','Do you know how to manage storage and clear space?',1,true,'tech-2',false,true,0,NOW()),
('tech-2-3','technology','Technology & Digital Skills','Can you set up parental controls or accessibility features?',1,true,'tech-2',false,true,0,NOW()),
('tech-2-4','technology','Technology & Digital Skills','Do you update apps and the operating system regularly?',1,true,'tech-2',false,true,0,NOW()),
('tech-3','technology','Technology & Digital Skills','How confident are you with word processing, spreadsheets, and presentations?',1,true,NULL,false,false,0,NOW()),
('tech-3-1','technology','Technology & Digital Skills','Can you use formulas and charts in spreadsheets?',1,true,'tech-3',false,true,0,NOW()),
('tech-3-2','technology','Technology & Digital Skills','Do you know how to collaborate on shared documents online?',1,true,'tech-3',false,true,0,NOW()),
('tech-3-3','technology','Technology & Digital Skills','Can you make a professional-looking presentation?',1,true,'tech-3',false,true,0,NOW()),
('tech-3-4','technology','Technology & Digital Skills','Do you know how to merge documents or export to PDF?',1,true,'tech-3',false,true,0,NOW()),
('tech-3-5','technology','Technology & Digital Skills','Can you use templates or basic automation to save time?',1,true,'tech-3',false,true,0,NOW()),
('tech-4','technology','Technology & Digital Skills','How confident are you using the internet safely and effectively?',1,true,NULL,false,false,0,NOW()),
('tech-4-1','technology','Technology & Digital Skills','Do you know how to shop online safely?',1,true,'tech-4',false,true,0,NOW()),
('tech-4-2','technology','Technology & Digital Skills','Can you spot suspicious websites or scams?',1,true,'tech-4',false,true,0,NOW()),
('tech-4-3','technology','Technology & Digital Skills','Do you use social media with privacy settings enabled?',1,true,'tech-4',false,true,0,NOW()),
('tech-4-4','technology','Technology & Digital Skills','Do you know how to manage cookies and browser settings?',1,true,'tech-4',false,true,0,NOW()),
('tech-4-5','technology','Technology & Digital Skills','Can you set up online banking or government digital services?',1,true,'tech-4',false,true,0,NOW()),
('tech-5','technology','Technology & Digital Skills','How confident are you with setting up and managing home internet?',1,true,NULL,false,false,0,NOW()),
('tech-5-1','technology','Technology & Digital Skills','Can you set up or reset a Wi-Fi router?',1,true,'tech-5',false,true,0,NOW()),
('tech-5-2','technology','Technology & Digital Skills','Do you know how to connect devices like printers or smart TVs?',1,true,'tech-5',false,true,0,NOW()),
('tech-5-3','technology','Technology & Digital Skills','Can you fix Wi-Fi problems such as weak signal or devices not connecting?',1,true,'tech-5',false,true,0,NOW()),
('tech-5-4','technology','Technology & Digital Skills','Do you know how to make your Wi-Fi secure with a strong password?',1,true,'tech-5',false,true,0,NOW()),
('tech-5-5','technology','Technology & Digital Skills','Can you set up a guest network for visitors?',1,true,'tech-5',false,true,0,NOW()),
('tech-6','technology','Technology & Digital Skills','How confident are you in keeping your accounts and data safe?',1,true,NULL,false,false,0,NOW()),
('tech-6-1','technology','Technology & Digital Skills','Do you use strong and unique passwords?',1,true,'tech-6',false,true,0,NOW()),
('tech-6-2','technology','Technology & Digital Skills','Do you know how to use two-factor authentication?',1,true,'tech-6',false,true,0,NOW()),
('tech-6-3','technology','Technology & Digital Skills','Can you recognise phishing emails or scam texts?',1,true,'tech-6',false,true,0,NOW()),
('tech-6-4','technology','Technology & Digital Skills','Do you update devices and software regularly for security?',1,true,'tech-6',false,true,0,NOW()),
('tech-6-5','technology','Technology & Digital Skills','Do you know how to safely dispose of an old phone or laptop?',1,true,'tech-6',false,true,0,NOW());
